baseURL: https://ftokoro.github.io/myblog
languageCode: ja
title: ftokoro's blog
canonifyurls: true
theme : "PaperMod"
publishDir: "docs"

params:
    defaultTheme: light #light or dark

    homeInfoParams:
        Title: Hello World!!
        Content: Can be Info, links, about...

    socialIcons:
        - name: "Github"
          url: "https://github.com/ftokoro"
        - name: "twitter"
          url: "https://twitter.com/FumiyaSoft"
