baseURL: https://ftokoro.github.io/
languageCode: ja
canonifyurls: true
title: ftokoro's blog
theme : PaperMod
publishDir: "docs"

params:
    defaultTheme: light #light or dark

    homeInfoParams:
        Title: Hello World!!
        Content: Welcome to my blog! 

    socialIcons:
        - name: "Github"
          url: "https://github.com/ftokoro"
        - name: "twitter"
          url: "https://twitter.com/FumiyaSoft"

    profileMode:
        enabled: true
        title: "About me"
        subtitle: "This is subtitle"
        imageUrl: "profile.png"        
        imageWidth: 120
        imageHeight: 120



